(function (global) {
  'use strict';

  const PAGE_WIDTH = 612;
  const PAGE_HEIGHT = 792;
  const LEFT = 42;

  function pdfEscape(value) {
    const replacements = {'–': '-', '—': '-', '’': "'", '‘': "'", '“': '"', '”': '"'};
    let result = '';
    for (const original of String(value ?? '')) {
      let char = replacements[original] || original;
      let code = char.charCodeAt(0);
      if (code > 255) {
        char = char.normalize('NFD').replace(/[\u0300-\u036f]/g, '')[0] || '?';
        code = char.charCodeAt(0);
        if (code > 255) { char = '?'; code = 63; }
      }
      if (char === '\\' || char === '(' || char === ')') result += `\\${char}`;
      else if (code < 32) result += ' ';
      else if (code > 126) result += `\\${code.toString(8).padStart(3, '0')}`;
      else result += char;
    }
    return result;
  }

  function clean(value, max = 42) {
    const text = String(value ?? '').trim() || '-';
    return text.length > max ? `${text.slice(0, max - 3)}...` : text;
  }

  function addText(commands, x, y, size, value, bold = false, color = '0.08 0.18 0.14') {
    commands.push(`${color} rg BT /${bold ? 'F2' : 'F1'} ${size} Tf ${x} ${y} Td (${pdfEscape(clean(value, 70))}) Tj ET`);
  }

  function addLine(commands, x1, y1, x2, y2, color = '0.84 0.85 0.81') {
    commands.push(`${color} RG 0.5 w ${x1} ${y1} m ${x2} ${y2} l S`);
  }

  function finishPdf(pages) {
    pages.forEach((page, index) => {
      addLine(page, LEFT, 39, 570, 39);
      addText(page, LEFT, 24, 8, 'Generated by PitchTrack', false, '0.45 0.49 0.47');
      addText(page, 525, 24, 8, `${index + 1} / ${pages.length}`, false, '0.45 0.49 0.47');
    });

    const objects = [];
    objects[1] = '<< /Type /Catalog /Pages 2 0 R >>';
    objects[3] = '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>';
    objects[4] = '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold /Encoding /WinAnsiEncoding >>';
    const pageIds = [];
    pages.forEach((page, index) => {
      const contentId = 5 + index * 2;
      const pageId = contentId + 1;
      pageIds.push(pageId);
      const stream = page.join('\n');
      objects[contentId] = `<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`;
      objects[pageId] = `<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${PAGE_WIDTH} ${PAGE_HEIGHT}] /Resources << /Font << /F1 3 0 R /F2 4 0 R >> >> /Contents ${contentId} 0 R >>`;
    });
    objects[2] = `<< /Type /Pages /Count ${pageIds.length} /Kids [${pageIds.map(id => `${id} 0 R`).join(' ')}] >>`;

    let pdf = '%PDF-1.4\n%\xE2\xE3\xCF\xD3\n';
    const offsets = [0];
    for (let id = 1; id < objects.length; id++) {
      offsets[id] = pdf.length;
      pdf += `${id} 0 obj\n${objects[id]}\nendobj\n`;
    }
    const xrefOffset = pdf.length;
    pdf += `xref\n0 ${objects.length}\n0000000000 65535 f \n`;
    for (let id = 1; id < objects.length; id++) pdf += `${String(offsets[id]).padStart(10, '0')} 00000 n \n`;
    pdf += `trailer\n<< /Size ${objects.length} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`;
    return Uint8Array.from(pdf, character => character.charCodeAt(0) & 255);
  }

  function createLineupsPdf(data) {
    const pages = [];
    let commands;
    let y;

    function newPage() {
      commands = [];
      pages.push(commands);
      commands.push('0.07 0.25 0.19 rg 0 744 612 48 re f');
      addText(commands, LEFT, 762, 20, 'PitchTrack - Game Lineups', true, '1 1 1');
      addText(commands, 445, 764, 9, data.date || 'Game day', false, '0.84 0.90 0.88');
      y = 718;
    }

    function ensureSpace(height, repeatHeader) {
      if (y - height >= 55) return;
      newPage();
      if (repeatHeader) repeatHeader();
    }

    function startPageIfUsed() {
      if (y < 640) newPage();
    }

    function sectionTitle(teamName, label) {
      ensureSpace(46);
      commands.push(`0.91 0.94 0.82 rg ${LEFT} ${y - 8} 528 30 re f`);
      addText(commands, LEFT + 11, y + 2, 14, `${teamName} - ${label}`, true);
      y -= 42;
    }

    function rosterSummary(teamName, batters, pitchers) {
      ensureSpace(50);
      addText(commands, LEFT, y, 13, teamName, true);
      addText(commands, 330, y, 9, `${batters.length} batters`, false, '0.40 0.45 0.42');
      addText(commands, 430, y, 9, `${pitchers.length} pitchers`, false, '0.40 0.45 0.42');
      y -= 18;
      addLine(commands, LEFT, y, 570, y, '0.78 0.82 0.76');
      y -= 18;
    }

    function batterHeader() {
      addText(commands, 50, y, 8, 'ORDER', true, '0.40 0.45 0.42');
      addText(commands, 96, y, 8, 'NO.', true, '0.40 0.45 0.42');
      addText(commands, 132, y, 8, 'PLAYER', true, '0.40 0.45 0.42');
      addText(commands, 410, y, 8, 'POS', true, '0.40 0.45 0.42');
      addText(commands, 490, y, 8, 'BATS', true, '0.40 0.45 0.42');
      y -= 12; addLine(commands, LEFT, y, 570, y); y -= 14;
    }

    function pitcherHeader() {
      addText(commands, 55, y, 8, 'NO.', true, '0.40 0.45 0.42');
      addText(commands, 105, y, 8, 'PITCHER', true, '0.40 0.45 0.42');
      addText(commands, 490, y, 8, 'THROWS', true, '0.40 0.45 0.42');
      y -= 12; addLine(commands, LEFT, y, 570, y); y -= 14;
    }

    function drawTeam(team, teamName) {
      const batters = (team.batters || []).filter(player => player.name);
      const pitchers = (team.pitchers || []).filter(player => player.name);
      startPageIfUsed();
      rosterSummary(teamName, batters, pitchers);
      sectionTitle(teamName, 'Batting Order');
      batterHeader();
      if (!batters.length) { addText(commands, 50, y, 10, 'No batting lineup entered'); y -= 24; }
      batters.forEach((player, index) => {
        ensureSpace(30, () => { sectionTitle(teamName, 'Batting Order - continued'); batterHeader(); });
        addText(commands, 58, y, 10, index + 1, true);
        addText(commands, 96, y, 10, player.number || '-');
        addText(commands, 132, y, 10, clean(player.name, 38));
        addText(commands, 410, y, 10, player.position || '-');
        addText(commands, 500, y, 10, player.bats || '-');
        y -= 13; addLine(commands, LEFT, y, 570, y, '0.91 0.91 0.88'); y -= 10;
      });

      ensureSpace(70);
      y -= 8;
      sectionTitle(teamName, 'Pitching Staff');
      pitcherHeader();
      if (!pitchers.length) { addText(commands, 50, y, 10, 'No pitching staff entered'); y -= 24; }
      pitchers.forEach((player) => {
        ensureSpace(30, () => { sectionTitle(teamName, 'Pitching Staff - continued'); pitcherHeader(); });
        addText(commands, 55, y, 10, player.number || '-');
        addText(commands, 105, y, 10, clean(player.name, 46));
        addText(commands, 505, y, 10, player.throws || '-');
        y -= 13; addLine(commands, LEFT, y, 570, y, '0.91 0.91 0.88'); y -= 10;
      });
      y -= 16;
    }

    newPage();
    addText(commands, LEFT, y, 13, `${data.awayName || 'Away'} at ${data.homeName || 'Home'}`, true);
    y -= 24;
    drawTeam(data.away || {}, data.awayName || 'Away Team');
    newPage();
    drawTeam(data.home || {}, data.homeName || 'Home Team');

    return finishPdf(pages);
  }

  function createStatsPdf(data) {
    const pages = [];
    let commands;
    let y;

    function newPage() {
      commands = [];
      pages.push(commands);
      commands.push('0.04 0.12 0.23 rg 0 744 612 48 re f');
      addText(commands, LEFT, 762, 20, 'PitchTrack - Live Stats', true, '1 1 1');
      addText(commands, 420, 764, 9, data.date || 'Game day', false, '0.84 0.90 1');
      y = 718;
    }

    function ensureSpace(height, repeatHeader) {
      if (y - height >= 55) return;
      newPage();
      if (repeatHeader) repeatHeader();
    }

    function startPageIfUsed() {
      if (y < 700) newPage();
    }

    function sectionTitle(label) {
      ensureSpace(42);
      commands.push(`0.84 0.91 1 rg ${LEFT} ${y - 8} 528 28 re f`);
      addText(commands, LEFT + 10, y + 1, 13, label, true, '0.04 0.12 0.23');
      y -= 39;
    }

    function row(values, xs, size = 8) {
      values.forEach((value, index) => addText(commands, xs[index], y, size, value, index === 0));
      y -= 12;
      addLine(commands, LEFT, y, 570, y, '0.90 0.91 0.88');
      y -= 8;
    }

    function table(title, headers, rows, xs, options = {}) {
      const estimatedHeight = 39 + 20 + Math.max(1, rows.length) * 20 + 10;
      if (options.keepTogether || estimatedHeight < 560) ensureSpace(estimatedHeight);
      sectionTitle(title);
      row(headers, xs, 7);
      if (!rows.length) { addText(commands, 50, y, 10, 'No stats yet'); y -= 24; return; }
      rows.forEach((values) => {
        ensureSpace(24, () => { sectionTitle(`${title} - continued`); row(headers, xs, 7); });
        row(values, xs, 8);
      });
      y -= 10;
    }

    function scorecard(teamCard) {
      const innings = teamCard.innings || [];
      const groups = [];
      for (let index = 0; index < innings.length; index += 6) groups.push(innings.slice(index, index + 6));
      (groups.length ? groups : [[]]).forEach((inningGroup, groupIndex) => {
        startPageIfUsed();
        const titleSuffix = groups.length > 1 ? ` (${inningGroup[0] || 1}-${inningGroup[inningGroup.length - 1] || 1})` : '';
        sectionTitle(`${teamCard.teamName} - AB by inning${titleSuffix}`);
        const xs = [48, 72, 230, ...inningGroup.map((_, i) => 275 + i * 43)];
        row(['#', 'Batter', 'Pos', ...inningGroup], xs, 7);
        (teamCard.players || []).forEach((player) => {
          ensureSpace(26, () => {
            sectionTitle(`${teamCard.teamName} - AB by inning continued${titleSuffix}`);
            row(['#', 'Batter', 'Pos', ...inningGroup], xs, 7);
          });
        const batter = `${player.number ? `#${player.number} ` : ''}${player.name}${player.note ? ` (${player.note})` : ''}`;
          row([player.order, batter, player.position || '-', ...inningGroup.map(inning => (player.cells?.[inning] || []).join(' '))], xs, 7);
        });
        if (groupIndex < groups.length - 1) newPage();
      });
      y -= 8;
    }

    newPage();
    addText(commands, LEFT, y, 13, `${data.awayName || 'Away'} at ${data.homeName || 'Home'}`, true);
    y -= 24;
    table('Team batting', ['Team','PA','AB','H','2B','3B','HR','BB','K','HBP','ROE','AVG'], data.teamRows || [], [48,150,185,220,250,280,310,340,370,400,438,475], {keepTogether: true});
    table('Pitchers', ['Pitcher','Team','P','Str%','H','BB','K','HBP','Outs'], data.pitcherRows || [], [48,180,260,295,335,365,395,425,465], {keepTogether: (data.pitcherRows || []).length <= 12});
    startPageIfUsed();
    table('Batters', ['Batter','Team','PA','AB','H','2B','3B','HR','BB','K','AVG'], data.batterRows || [], [48,170,245,275,305,335,365,395,425,455,490]);
    startPageIfUsed();
    scorecard(data.awayScorecard || {teamName: data.awayName || 'Away', innings: [], players: []});
    startPageIfUsed();
    scorecard(data.homeScorecard || {teamName: data.homeName || 'Home', innings: [], players: []});
    startPageIfUsed();
    table('Pitch types', ['Pitch','Total','Str%','Avg','Whiff','In play'], data.pitchTypeRows || [], [48,180,225,270,315,365], {keepTogether: true});
    return finishPdf(pages);
  }

  global.createLineupsPdf = createLineupsPdf;
  global.createStatsPdf = createStatsPdf;
  if (typeof module !== 'undefined' && module.exports) module.exports = {createLineupsPdf, createStatsPdf};
})(typeof window !== 'undefined' ? window : globalThis);
