(function (global) {
  'use strict';

  const PAGE_WIDTH = 612;
  const PAGE_HEIGHT = 792;
  const LEFT = 42;

  function pdfEscape(value) {
    const replacements = {'–': '-', '—': '-', '’': "'", '‘': "'", '“': '"', '”': '"'};
    let result = '';
    for (const original of String(value ?? '')) {
      let char = replacements[original] || original;
      let code = char.charCodeAt(0);
      if (code > 255) {
        char = char.normalize('NFD').replace(/[\u0300-\u036f]/g, '')[0] || '?';
        code = char.charCodeAt(0);
        if (code > 255) { char = '?'; code = 63; }
      }
      if (char === '\\' || char === '(' || char === ')') result += `\\${char}`;
      else if (code < 32) result += ' ';
      else if (code > 126) result += `\\${code.toString(8).padStart(3, '0')}`;
      else result += char;
    }
    return result;
  }

  function clean(value, max = 42) {
    const text = String(value ?? '').trim() || '-';
    return text.length > max ? `${text.slice(0, max - 3)}...` : text;
  }

  function addText(commands, x, y, size, value, bold = false, color = '0.08 0.18 0.14') {
    commands.push(`${color} rg BT /${bold ? 'F2' : 'F1'} ${size} Tf ${x} ${y} Td (${pdfEscape(clean(value, 70))}) Tj ET`);
  }

  function addLine(commands, x1, y1, x2, y2, color = '0.84 0.85 0.81') {
    commands.push(`${color} RG 0.5 w ${x1} ${y1} m ${x2} ${y2} l S`);
  }

  function createLineupsPdf(data) {
    const pages = [];
    let commands;
    let y;

    function newPage() {
      commands = [];
      pages.push(commands);
      commands.push('0.07 0.25 0.19 rg 0 744 612 48 re f');
      addText(commands, LEFT, 762, 20, 'PitchTrack - Game Lineups', true, '1 1 1');
      addText(commands, 445, 764, 9, data.date || 'Game day', false, '0.84 0.90 0.88');
      y = 718;
    }

    function ensureSpace(height, repeatHeader) {
      if (y - height >= 55) return;
      newPage();
      if (repeatHeader) repeatHeader();
    }

    function sectionTitle(teamName, label) {
      ensureSpace(46);
      commands.push(`0.91 0.94 0.82 rg ${LEFT} ${y - 8} 528 30 re f`);
      addText(commands, LEFT + 11, y + 2, 14, `${teamName} - ${label}`, true);
      y -= 42;
    }

    function batterHeader() {
      addText(commands, 50, y, 8, 'ORDER', true, '0.40 0.45 0.42');
      addText(commands, 96, y, 8, 'NO.', true, '0.40 0.45 0.42');
      addText(commands, 132, y, 8, 'PLAYER', true, '0.40 0.45 0.42');
      addText(commands, 410, y, 8, 'POS', true, '0.40 0.45 0.42');
      addText(commands, 490, y, 8, 'BATS', true, '0.40 0.45 0.42');
      y -= 12; addLine(commands, LEFT, y, 570, y); y -= 14;
    }

    function pitcherHeader() {
      addText(commands, 55, y, 8, 'NO.', true, '0.40 0.45 0.42');
      addText(commands, 105, y, 8, 'PITCHER', true, '0.40 0.45 0.42');
      addText(commands, 490, y, 8, 'THROWS', true, '0.40 0.45 0.42');
      y -= 12; addLine(commands, LEFT, y, 570, y); y -= 14;
    }

    function drawTeam(team, teamName) {
      const batters = (team.batters || []).filter(player => player.name);
      sectionTitle(teamName, 'Batting Order');
      batterHeader();
      if (!batters.length) { addText(commands, 50, y, 10, 'No batting lineup entered'); y -= 24; }
      batters.forEach((player, index) => {
        ensureSpace(30, () => { sectionTitle(teamName, 'Batting Order - continued'); batterHeader(); });
        addText(commands, 58, y, 10, index + 1, true);
        addText(commands, 96, y, 10, player.number || '-');
        addText(commands, 132, y, 10, clean(player.name, 38));
        addText(commands, 410, y, 10, player.position || '-');
        addText(commands, 500, y, 10, player.bats || '-');
        y -= 13; addLine(commands, LEFT, y, 570, y, '0.91 0.91 0.88'); y -= 10;
      });

      ensureSpace(70);
      y -= 8;
      sectionTitle(teamName, 'Pitching Staff');
      pitcherHeader();
      const pitchers = (team.pitchers || []).filter(player => player.name);
      if (!pitchers.length) { addText(commands, 50, y, 10, 'No pitching staff entered'); y -= 24; }
      pitchers.forEach((player) => {
        ensureSpace(30, () => { sectionTitle(teamName, 'Pitching Staff - continued'); pitcherHeader(); });
        addText(commands, 55, y, 10, player.number || '-');
        addText(commands, 105, y, 10, clean(player.name, 46));
        addText(commands, 505, y, 10, player.throws || '-');
        y -= 13; addLine(commands, LEFT, y, 570, y, '0.91 0.91 0.88'); y -= 10;
      });
      y -= 16;
    }

    newPage();
    drawTeam(data.away || {}, data.awayName || 'Away Team');
    ensureSpace(120);
    drawTeam(data.home || {}, data.homeName || 'Home Team');

    pages.forEach((page, index) => {
      addLine(page, LEFT, 39, 570, 39);
      addText(page, LEFT, 24, 8, 'Generated by PitchTrack', false, '0.45 0.49 0.47');
      addText(page, 525, 24, 8, `${index + 1} / ${pages.length}`, false, '0.45 0.49 0.47');
    });

    const objects = [];
    objects[1] = '<< /Type /Catalog /Pages 2 0 R >>';
    objects[3] = '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>';
    objects[4] = '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold /Encoding /WinAnsiEncoding >>';
    const pageIds = [];
    pages.forEach((page, index) => {
      const contentId = 5 + index * 2;
      const pageId = contentId + 1;
      pageIds.push(pageId);
      const stream = page.join('\n');
      objects[contentId] = `<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`;
      objects[pageId] = `<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${PAGE_WIDTH} ${PAGE_HEIGHT}] /Resources << /Font << /F1 3 0 R /F2 4 0 R >> >> /Contents ${contentId} 0 R >>`;
    });
    objects[2] = `<< /Type /Pages /Count ${pageIds.length} /Kids [${pageIds.map(id => `${id} 0 R`).join(' ')}] >>`;

    let pdf = '%PDF-1.4\n%\xE2\xE3\xCF\xD3\n';
    const offsets = [0];
    for (let id = 1; id < objects.length; id++) {
      offsets[id] = pdf.length;
      pdf += `${id} 0 obj\n${objects[id]}\nendobj\n`;
    }
    const xrefOffset = pdf.length;
    pdf += `xref\n0 ${objects.length}\n0000000000 65535 f \n`;
    for (let id = 1; id < objects.length; id++) pdf += `${String(offsets[id]).padStart(10, '0')} 00000 n \n`;
    pdf += `trailer\n<< /Size ${objects.length} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`;
    return Uint8Array.from(pdf, character => character.charCodeAt(0) & 255);
  }

  global.createLineupsPdf = createLineupsPdf;
  if (typeof module !== 'undefined' && module.exports) module.exports = {createLineupsPdf};
})(typeof window !== 'undefined' ? window : globalThis);
